### ISSUE TITLE
Offline Players [SOLVED]

### ISSUE THREAD

**Issue by Stualyttle** [NoahNok/ClaimDonation#1]
Hi,

_I have set this plugin in my lobby server, and it works like a sharm!
But theres one problem.. When that player is not online, it doesn't work
When hes online and i try the same command it works again.._

Sorry i just wanted to report this :D 

Greets
Stualyttle Kirry
_(sorry for bad english i'm dutch)*_

**Comment by NoahNok** [comment]
Fixed, and thank you for notifying me of this!
